### ISSUE TITLE
Jicofo file descriptor leaks

### ISSUE THREAD

**Issue by cs35-owncloud** [jitsi/jicofo#561]
Hello everyone,

after some tests, I've noticed that jicofo installed with docker eats up many many file descriptors for nothing. I found several threads about file descriptor leaks in jitsi-meet, but it seems it was related to the jvb and has been fixed. This new problem is purely jicofo related or docker jicofo related.

## Configuration

* OS: Debian 10
* Environment: docker jitsi (latest)
```
root@xxx.xxx [xxx]:~ # dpkg -l | grep -E 'docker.io|docker-compose'
ii  docker-compose                   1.21.0-3                     all          Punctual, lightweight development environments using Docker
ii  docker.io                        18.09.1+dfsg1-7.1+deb10u1    amd64        Linux container runtime
ii  python3-docker                   3.4.1-4                      all          Python 3 wrapper to access docker.io's control socket

```
* Jicofo: latest
```
root@xxx.xxx [xxx]:~ # docker ps | grep jicofo
d893f7c24900        jitsi/jicofo:latest   "/init"                  2 hours ago         Up 7 minutes                                   jitsi_jicofo_1
```
* docker-compose.yml (only the jicofo part):

```
    # Focus component
    jicofo:
        image: jitsi/jicofo:latest
        restart: ${RESTART_POLICY}
        volumes:
            - ${CONFIG}/jicofo:/config:Z
        environment:
            - ENABLE_AUTH
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JICOFO_RESERVATION_REST_BASE_URL
            - JVB_BREWERY_MUC
            - JIGASI_BREWERY_MUC
            - JIGASI_SIP_URI
            - JIBRI_BREWERY_MUC
            - JIBRI_PENDING_TIMEOUT
            - TZ
        depends_on:
            - prosody
        networks:
            meet.jitsi:
```
## Test

* Check how many file descriptors are used

```
root@xxx.xxx [xxx]:~ # lsof | wc -l
30081
```

* Start only jicofo

```
root@xxx.xxx [xxx]:~ # docker start $(docker container ls -a | grep -i jicofo | awk '{ print $1 }')
d893f7c24900
```

* Check the file descriptors usage

```
root@xxx.xxx [xxx]:~ # date && lsof | wc -l
mercredi 1 juillet 2020, 13:47:48 (UTC+0200)
44057
```

* And again

```
root@xxx.xxx [xxx]:~ # date && lsof | wc -l
mercredi 1 juillet 2020, 13:48:11 (UTC+0200)
46033
```
* And again

```
root@xxx.xxx [xxx]:~ # date && lsof | wc -l
mercredi 1 juillet 2020, 13:54:51 (UTC+0200)
77284
```

It goes UP alone even though there are no rooms being used, only Jicofo is running and eats all file descriptors. It never stops increasing.

Do you need more information on the subject ? Could you please fix this, it's a huge problem, I had 600000 file descriptors on an instance with an uptime of 44 hours ....
Thanks.
